import 'dotenv/config';
import { inArray, sql } from 'drizzle-orm';
import { db, setDatabaseSessionTimeZone } from './db/index.js';
import { cashTransactions, customers, employees, items, pawns, settings } from './db/schema.js';
import { GOLD_JEWELLERY_ITEM_TYPE, getStorageInfo, } from '../../shared/storage/storageUtils.js';
const SEED_TAG = '[seed:demo]';
const SEED_COUNT = Number(process.env.SEED_COUNT || 48);
const DB_TIMEZONE = process.env.SEED_DB_TIMEZONE || 'Asia/Bangkok';
const DB_TIMEZONE_KEY = 'db_timezone';
const APP_SETTINGS_KEY = 'app_settings';
const DAY_MS = 24 * 60 * 60 * 1000;
const itemTypeCatalog = [
    GOLD_JEWELLERY_ITEM_TYPE,
    'Phone',
    'Motorcycle',
    'Electronics',
    'Watch',
    'Other',
];
const interestTiers = [
    { minAmount: 0, rate: 3 },
    { minAmount: 500001, rate: 2.5 },
    { minAmount: 1000001, rate: 2 },
];
const appSettings = {
    interestTiers,
    interestTiersByItemType: Object.fromEntries(itemTypeCatalog.map((itemType, index) => [
        itemType,
        interestTiers.map((tier) => ({
            ...tier,
            rate: itemType === GOLD_JEWELLERY_ITEM_TYPE
                ? tier.rate
                : Number((tier.rate + 1 + (index % 2) * 0.5).toFixed(1)),
        })),
    ])),
    goldRate: '80000',
    oneKyatInGrams: '16.606',
    goldPricePerKyat: '1328480',
    itemTypes: [...itemTypeCatalog],
    itemDescriptionPresets: {
        [GOLD_JEWELLERY_ITEM_TYPE]: ['Gold ring', 'Gold necklace', 'Gold bracelet', 'Gold earrings'],
        Phone: ['iPhone', 'Samsung phone', 'Oppo phone', 'Xiaomi phone'],
        Motorcycle: ['Honda motorcycle', 'Yamaha motorcycle', 'E-bike'],
        Electronics: ['Laptop', 'Tablet', 'Camera'],
        Watch: ['Gold watch', 'Smart watch', 'Analog watch'],
        Other: ['Household item', 'Tool set', 'Bag'],
    },
    itemOverdueThresholds: Object.fromEntries(itemTypeCatalog.map((itemType) => [itemType, { months: 4, days: 0 }])),
    faceCameraId: '',
    ticketCameraId: '',
    dbTimeZone: DB_TIMEZONE,
};
const demoCustomers = [
    ['Aung Ko Ko', 'No. 12, 38th Street, Kyauktada, Yangon', '0912345001', '12/KYATA(N)100001'],
    ['Su Mon Hlaing', 'No. 22, Baho Road, Sanchaung, Yangon', '0912345002', '12/SACHA(N)100002'],
    ['Myo Min Thu', 'No. 8, Strand Road, Mawlamyine', '0912345003', '10/MALAMA(N)100003'],
    ['Thiri Aye', 'No. 41, 26th Street, Mandalay', '0912345004', '9/MAHAMA(N)100004'],
    ['Nanda Kyaw', 'No. 6, Clock Tower Road, Bago', '0912345005', '7/BAGANA(N)100005'],
    ['Ei Phyu Zin', 'No. 19, Myoma Market Street, Pathein', '0912345006', '14/PATHANA(N)100006'],
    ['Ko Htet Naing', 'No. 55, Bayint Naung Road, Hlaing, Yangon', '0912345007', '12/HALANA(N)100007'],
    ['May Zin Oo', 'No. 3, Kan Nar Road, Taunggyi', '0912345008', '13/TATANA(N)100008'],
];
const descriptionsByType = {
    [GOLD_JEWELLERY_ITEM_TYPE]: [
        '22K gold ring with simple band',
        'Gold necklace with pendant',
        'Pair of gold earrings',
        'Gold bracelet with clasp',
    ],
    Phone: ['iPhone 13 128GB', 'Samsung Galaxy A series', 'Oppo Reno handset', 'Xiaomi Redmi phone'],
    Motorcycle: ['Honda Click motorcycle', 'Yamaha Fino motorcycle', 'Honda Wave motorcycle'],
    Electronics: ['Lenovo laptop', 'Canon digital camera', 'iPad tablet'],
    Watch: ['Citizen analog watch', 'Apple Watch', 'Seiko dress watch'],
    Other: ['Singer sewing machine', 'Power tool set', 'Leather travel bag'],
};
async function ensureTablesExist() {
    await db.execute(sql `
        CREATE TABLE IF NOT EXISTS employees (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text NOT NULL,
            user_name text NOT NULL UNIQUE,
            password text NOT NULL,
            level text NOT NULL
        )
    `);
    await db.execute(sql `
        CREATE TABLE IF NOT EXISTS customers (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text NOT NULL,
            address text NOT NULL,
            phone text,
            description text,
            remark text,
            photo text,
            face_descriptor text
        )
    `);
    await db.execute(sql `ALTER TABLE customers ADD COLUMN IF NOT EXISTS remark text`);
    await db.execute(sql `ALTER TABLE customers ADD COLUMN IF NOT EXISTS photo text`);
    await db.execute(sql `ALTER TABLE customers ADD COLUMN IF NOT EXISTS face_descriptor text`);
    await db.execute(sql `
        CREATE TABLE IF NOT EXISTS items (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            status text NOT NULL,
            description text,
            type text NOT NULL,
            photo text,
            gross_weight real,
            net_weight real,
            jewellery_type text,
            daily_serial integer,
            store_index text,
            number integer,
            item_other_type text
        )
    `);
    await db.execute(sql `ALTER TABLE items ADD COLUMN IF NOT EXISTS photo text`);
    await db.execute(sql `
        CREATE TABLE IF NOT EXISTS pawns (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            interest_rate real,
            max_available_amount integer,
            description text,
            note text,
            customer_fk integer NOT NULL REFERENCES customers(id),
            item_fk integer REFERENCES items(id),
            physical_number text,
            storage_location text,
            box_number integer,
            tray_number integer,
            day_of_month integer,
            sequence integer,
            slot_number integer,
            last_payment_date timestamp
        )
    `);
    await db.execute(sql `ALTER TABLE pawns ADD COLUMN IF NOT EXISTS note text`);
    await db.execute(sql `ALTER TABLE pawns ADD COLUMN IF NOT EXISTS physical_number text`);
    await db.execute(sql `ALTER TABLE pawns ADD COLUMN IF NOT EXISTS storage_location text`);
    await db.execute(sql `ALTER TABLE pawns ADD COLUMN IF NOT EXISTS box_number integer`);
    await db.execute(sql `ALTER TABLE pawns ADD COLUMN IF NOT EXISTS tray_number integer`);
    await db.execute(sql `ALTER TABLE pawns ADD COLUMN IF NOT EXISTS day_of_month integer`);
    await db.execute(sql `ALTER TABLE pawns ADD COLUMN IF NOT EXISTS sequence integer`);
    await db.execute(sql `ALTER TABLE pawns ADD COLUMN IF NOT EXISTS slot_number integer`);
    await db.execute(sql `ALTER TABLE pawns ADD COLUMN IF NOT EXISTS last_payment_date timestamp`);
    await db.execute(sql `
        CREATE TABLE IF NOT EXISTS cash_transactions (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            date timestamp DEFAULT now(),
            type text NOT NULL,
            amount integer NOT NULL,
            discount integer DEFAULT 0,
            description text,
            pawn_fk integer NOT NULL REFERENCES pawns(id),
            employee_fk integer REFERENCES employees(id)
        )
    `);
    await db.execute(sql `
        CREATE TABLE IF NOT EXISTS settings (
            key text PRIMARY KEY,
            value text NOT NULL
        )
    `);
}
async function removePreviousDemoSeed() {
    await db.execute(sql `
        DELETE FROM cash_transactions
        WHERE pawn_fk IN (
            SELECT p.id
            FROM pawns p
            WHERE p.description LIKE ${`${SEED_TAG}%`}
        )
    `);
    await db.execute(sql `DELETE FROM pawns WHERE description LIKE ${`${SEED_TAG}%`}`);
    await db.execute(sql `DELETE FROM items WHERE description LIKE ${`${SEED_TAG}%`}`);
    await db.execute(sql `DELETE FROM customers WHERE remark = ${SEED_TAG}`);
}
const daysAgo = (days) => new Date(Date.now() - days * DAY_MS);
const amountForIndex = (idx) => {
    const bands = [75000, 120000, 180000, 250000, 350000, 500000, 750000, 1200000];
    return bands[idx % bands.length] + Math.floor(idx / bands.length) * 25000;
};
const rateFor = (itemType, amount) => {
    if (itemType === GOLD_JEWELLERY_ITEM_TYPE)
        return amount > 1_000_000 ? 2 : amount > 500_000 ? 2.5 : 3;
    if (itemType === 'Motorcycle')
        return 5;
    if (itemType === 'Phone')
        return 4;
    return 4.5;
};
const getItemDescription = (itemType, idx) => {
    const descriptions = descriptionsByType[itemType] ?? descriptionsByType.Other;
    return descriptions[idx % descriptions.length];
};
async function seedEmployees() {
    await db
        .insert(employees)
        .values([
        { name: 'Admin User', userName: 'admin', password: 'password', level: 'Admin' },
        { name: 'Staff User', userName: 'staff', password: 'password', level: 'Staff' },
        { name: 'Cashier Demo', userName: 'cashier', password: 'password', level: 'Staff' },
    ])
        .onConflictDoNothing();
    const rows = await db.select({ id: employees.id, userName: employees.userName }).from(employees);
    const admin = rows.find((row) => row.userName === 'admin') ?? rows[0];
    if (!admin)
        throw new Error('No employee exists after employee seed');
    return admin.id;
}
async function seedSettings() {
    await setDatabaseSessionTimeZone(DB_TIMEZONE);
    await db
        .insert(settings)
        .values([
        { key: DB_TIMEZONE_KEY, value: DB_TIMEZONE },
        { key: APP_SETTINGS_KEY, value: JSON.stringify(appSettings) },
    ])
        .onConflictDoUpdate({
        target: settings.key,
        set: { value: sql `excluded.value` },
    });
}
async function seedCustomers() {
    const rows = Array.from({ length: SEED_COUNT }, (_, idx) => {
        const template = demoCustomers[idx % demoCustomers.length];
        const cycle = Math.floor(idx / demoCustomers.length);
        return {
            name: cycle === 0 ? template[0] : `${template[0]} ${cycle + 1}`,
            address: template[1],
            phone: `09${String(12345001 + idx).padStart(8, '0')}`,
            description: `NRC: ${template[3]}`,
            remark: SEED_TAG,
        };
    });
    return db.insert(customers).values(rows).returning({ id: customers.id });
}
async function seedItems() {
    const rows = Array.from({ length: SEED_COUNT }, (_, idx) => {
        const itemType = itemTypeCatalog[idx % itemTypeCatalog.length];
        const isGold = itemType === GOLD_JEWELLERY_ITEM_TYPE;
        const grossWeight = isGold ? Number((1.25 + (idx % 10) * 0.36).toFixed(2)) : null;
        return {
            status: idx % 11 === 0 ? 'EXPIRED' : 'PAWN',
            description: `${SEED_TAG} ${getItemDescription(itemType, idx)}`,
            type: itemType,
            grossWeight,
            netWeight: isGold && grossWeight != null ? Number((grossWeight * 0.92).toFixed(2)) : null,
            jewelleryType: isGold ? (idx % 2 === 0 ? '22K Gold' : '18K Gold') : null,
            dailySerial: idx + 1,
            storeIndex: isGold ? `G-${String((idx % 24) + 1).padStart(2, '0')}` : null,
            number: isGold ? null : 2000 + idx,
            itemOtherType: isGold ? null : itemType,
        };
    });
    return db.insert(items).values(rows).returning({ id: items.id });
}
async function seedPawns(insertedCustomers, insertedItems, employeeId) {
    const pawnRows = Array.from({ length: SEED_COUNT }, (_, idx) => {
        const itemType = itemTypeCatalog[idx % itemTypeCatalog.length];
        const isGold = itemType === GOLD_JEWELLERY_ITEM_TYPE;
        const amount = amountForIndex(idx);
        const openedAt = daysAgo(7 + (idx % 18) * 6);
        const lastPaymentDate = daysAgo(idx % 5 === 0 ? 95 : idx % 4 === 0 ? 45 : idx % 3 === 0 ? 18 : 0);
        const storage = isGold ? getStorageInfo(openedAt, idx % 3) : null;
        return {
            interestRate: rateFor(itemType, amount),
            maxAvailableAmount: amount,
            description: `${SEED_TAG} Demo pawn contract ${String(idx + 1).padStart(3, '0')}`,
            note: idx % 7 === 0 ? 'Demo ticket with follow-up note' : null,
            customerFk: insertedCustomers[idx].id,
            itemFk: insertedItems[idx].id,
            physicalNumber: isGold ? null : `${String.fromCharCode(65 + (idx % 4))} ${100 + idx}`,
            storageLocation: storage?.storageLocation ?? null,
            boxNumber: storage?.boxNumber ?? null,
            trayNumber: storage?.trayNumber ?? null,
            dayOfMonth: storage?.dayOfMonth ?? null,
            sequence: storage?.sequence ?? null,
            slotNumber: storage?.slotNumber ?? null,
            lastPaymentDate,
        };
    });
    const insertedPawns = await db.insert(pawns).values(pawnRows).returning({ id: pawns.id });
    const openingTransactions = pawnRows.map((pawn, idx) => ({
        type: 'PAWN',
        amount: pawn.maxAvailableAmount,
        discount: 0,
        description: `${SEED_TAG} Initial pawn disbursement ${String(idx + 1).padStart(3, '0')}`,
        pawnFk: insertedPawns[idx].id,
        employeeFk: employeeId,
        date: daysAgo(7 + (idx % 18) * 6),
    }));
    const interestTransactions = insertedPawns
        .map((pawn, idx) => {
        if (idx % 3 !== 0)
            return null;
        const amount = Math.round((pawnRows[idx].maxAvailableAmount * pawnRows[idx].interestRate) / 100);
        return {
            type: 'PAID_INTEREST',
            amount,
            discount: idx % 9 === 0 ? 500 : 0,
            description: `${SEED_TAG} Demo interest payment ${String(idx + 1).padStart(3, '0')}`,
            pawnFk: pawn.id,
            employeeFk: employeeId,
            date: daysAgo(2 + (idx % 12)),
        };
    })
        .filter((row) => row != null);
    const redeemedTransactions = insertedPawns
        .flatMap((pawn, idx) => {
        if (idx % 13 !== 0)
            return [];
        return [
            {
                type: 'REDEEM_BA',
                amount: pawnRows[idx].maxAvailableAmount,
                discount: 0,
                description: `${SEED_TAG} Demo redeemed principal ${String(idx + 1).padStart(3, '0')}`,
                pawnFk: pawn.id,
                employeeFk: employeeId,
                date: daysAgo(1 + (idx % 7)),
            },
            {
                type: 'REDEEM_I',
                amount: Math.round((pawnRows[idx].maxAvailableAmount * pawnRows[idx].interestRate) / 100),
                discount: 0,
                description: `${SEED_TAG} Demo redeemed interest ${String(idx + 1).padStart(3, '0')}`,
                pawnFk: pawn.id,
                employeeFk: employeeId,
                date: daysAgo(1 + (idx % 7)),
            },
        ];
    });
    await db.insert(cashTransactions).values([
        ...openingTransactions,
        ...interestTransactions,
        ...redeemedTransactions,
    ]);
    const redeemedItemIds = insertedItems
        .filter((_, idx) => idx % 13 === 0)
        .map((item) => item.id);
    if (redeemedItemIds.length > 0) {
        await db.update(items).set({ status: 'REDEEMED' }).where(inArray(items.id, redeemedItemIds));
    }
    return {
        pawnCount: insertedPawns.length,
        transactionCount: openingTransactions.length + interestTransactions.length + redeemedTransactions.length,
        interestCount: interestTransactions.length,
        redeemedCount: redeemedTransactions.filter((tx) => tx.type === 'REDEEM_BA').length,
    };
}
async function seed() {
    console.log('Ensuring tables exist...');
    await ensureTablesExist();
    console.log('Removing previous demo seed rows...');
    await removePreviousDemoSeed();
    console.log('Seeding employees and settings...');
    const employeeId = await seedEmployees();
    await seedSettings();
    console.log(`Seeding ${SEED_COUNT} customers...`);
    const insertedCustomers = await seedCustomers();
    console.log(`Seeding ${SEED_COUNT} items...`);
    const insertedItems = await seedItems();
    console.log(`Seeding ${SEED_COUNT} pawns and transactions...`);
    const pawnSummary = await seedPawns(insertedCustomers, insertedItems, employeeId);
    console.log('\nSeed complete!');
    console.log(`  Time zone       : ${DB_TIMEZONE}`);
    console.log(`  Customers       : ${insertedCustomers.length}`);
    console.log(`  Items           : ${insertedItems.length}`);
    console.log(`  Pawns           : ${pawnSummary.pawnCount}`);
    console.log(`  Cash txns       : ${pawnSummary.transactionCount}`);
    console.log(`  Interest txns   : ${pawnSummary.interestCount}`);
    console.log(`  Redeemed pawns  : ${pawnSummary.redeemedCount}`);
}
seed()
    .catch((err) => {
    console.error('Seed failed:', err);
    process.exitCode = 1;
})
    .finally(() => process.exit());
