import 'dotenv/config';
import { db } from './db/index.js';
import { cashTransactions, customers, employees, items, pawns } from './db/schema.js';
import { sql } from 'drizzle-orm';

const SEED_COUNT = 100;

async function ensureTablesExist() {
    await db.execute(sql`
        CREATE TABLE IF NOT EXISTS employees (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text NOT NULL,
            user_name text NOT NULL UNIQUE,
            password text NOT NULL,
            level text NOT NULL
        )
    `);
    await db.execute(sql`
        CREATE TABLE IF NOT EXISTS customers (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text NOT NULL,
            address text NOT NULL,
            phone text,
            description text,
            remark text
        )
    `);
    await db.execute(sql`
        CREATE TABLE IF NOT EXISTS items (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            status text NOT NULL,
            description text,
            type text NOT NULL,
            photo text,
            gross_weight real,
            net_weight real,
            jewellery_type text,
            daily_serial integer,
            store_index text,
            number integer,
            item_other_type text
        )
    `);
    await db.execute(sql`
        CREATE TABLE IF NOT EXISTS pawns (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            interest_rate real,
            max_available_amount integer,
            description text,
            note text,
            customer_fk integer NOT NULL REFERENCES customers(id),
            item_fk integer REFERENCES items(id),
            physical_number text,
            storage_location text,
            slot_number integer,
            last_payment_date timestamp
        )
    `);
    await db.execute(sql`ALTER TABLE pawns ADD COLUMN IF NOT EXISTS note text`);
    await db.execute(sql`
        CREATE TABLE IF NOT EXISTS cash_transactions (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            date timestamp DEFAULT now(),
            type text NOT NULL,
            amount integer NOT NULL,
            discount integer DEFAULT 0,
            description text,
            pawn_fk integer NOT NULL REFERENCES pawns(id),
            employee_fk integer REFERENCES employees(id)
        )
    `);
}

async function seed() {
    console.log('Ensuring tables exist...');
    await ensureTablesExist();

    // Seed employees
    console.log('Seeding employees...');
    await db
        .insert(employees)
        .values([
            { name: 'Admin User', userName: 'admin', password: 'password', level: 'Admin' },
            { name: 'Staff One', userName: 'staff1', password: 'password', level: 'Staff' },
            { name: 'Staff Two', userName: 'staff2', password: 'password', level: 'Staff' },
        ])
        .onConflictDoNothing();

    const allEmployees = await db.select({ id: employees.id }).from(employees);
    const employeeId = allEmployees[0].id;

    // Seed customers
    console.log(`Seeding ${SEED_COUNT} customers...`);
    const customerRows = Array.from({ length: SEED_COUNT }, (_, idx) => ({
        name: `Customer ${idx + 1}`,
        address: `${(idx % 50) + 1} Main Street, Township ${(idx % 10) + 1}`,
        phone: `09${String(10000000 + idx).padStart(8, '0')}`,
        description: `NRC: 12/${['MAMANA', 'TATANA', 'NANANA'][idx % 3]}(N)${String(100000 + idx)}`,
    }));
    const insertedCustomers = await db.insert(customers).values(customerRows).returning({ id: customers.id });

    // Seed items
    console.log(`Seeding ${SEED_COUNT} items...`);
    const itemRows = Array.from({ length: SEED_COUNT }, (_, idx) => {
        const itemType = idx % 3 === 0 ? 'J' : idx % 3 === 1 ? 'I' : 'O';
        return {
            status: 'PAWN',
            description: `Mock item #${idx + 1}`,
            type: itemType,
            grossWeight: itemType === 'J' ? Number((1.2 + (idx % 8) * 0.25).toFixed(2)) : null,
            netWeight: itemType === 'J' ? Number((1.0 + (idx % 8) * 0.2).toFixed(2)) : null,
            jewelleryType: itemType === 'J' ? (idx % 2 === 0 ? 'Gold' : 'Silver') : null,
            dailySerial: idx + 1,
            storeIndex: `S-${String((idx % 20) + 1).padStart(2, '0')}`,
            number: itemType !== 'J' ? 1000 + idx : null,
            itemOtherType: itemType !== 'J' ? (idx % 2 === 0 ? 'Electronics' : 'Vehicle') : null,
        };
    });
    const insertedItems = await db.insert(items).values(itemRows).returning({ id: items.id });

    // Seed pawns
    console.log(`Seeding ${SEED_COUNT} pawns...`);
    const pawnRows = Array.from({ length: SEED_COUNT }, (_, idx) => ({
        interestRate: 5 + (idx % 4),
        maxAvailableAmount: 50000 + (idx % 10) * 25000,
        description: `Mock pawn contract #${idx + 1}`,
        customerFk: insertedCustomers[idx].id,
        itemFk: insertedItems[idx].id,
        physicalNumber: `A ${idx + 1}`,
        storageLocation: `Rack-${(idx % 12) + 1}`,
        slotNumber: (idx % 40) + 1,
        lastPaymentDate: new Date(Date.now() - (idx % 60) * 24 * 60 * 60 * 1000),
    }));
    const insertedPawns = await db.insert(pawns).values(pawnRows).returning({ id: pawns.id });

    // Seed initial pawn loan cash transactions
    console.log(`Seeding ${SEED_COUNT} cash transactions...`);
    const txRows = Array.from({ length: SEED_COUNT }, (_, idx) => ({
        type: 'PAWN',
        amount: pawnRows[idx].maxAvailableAmount,
        discount: 0,
        description: `Initial pawn loan disbursement #${idx + 1}`,
        pawnFk: insertedPawns[idx].id,
        employeeFk: employeeId,
        date: new Date(Date.now() - (idx % 60) * 24 * 60 * 60 * 1000),
    }));
    await db.insert(cashTransactions).values(txRows);

    // Seed some interest payment transactions for variety
    console.log('Seeding interest payment transactions...');
    const interestTxRows = Array.from({ length: Math.floor(SEED_COUNT / 3) }, (_, idx) => ({
        type: 'PAID_INTEREST',
        amount: (5 + (idx % 4)) * Math.floor((50000 + (idx % 10) * 25000) / 100),
        discount: 0,
        description: `Interest payment for pawn #${idx + 1}`,
        pawnFk: insertedPawns[idx].id,
        employeeFk: employeeId,
        date: new Date(Date.now() - (idx % 30) * 24 * 60 * 60 * 1000),
    }));
    await db.insert(cashTransactions).values(interestTxRows);

    console.log('\nSeed complete!');
    console.log(`  Employees : ${allEmployees.length}`);
    console.log(`  Customers : ${SEED_COUNT}`);
    console.log(`  Items     : ${SEED_COUNT}`);
    console.log(`  Pawns     : ${SEED_COUNT}`);
    console.log(`  Cash txns : ${SEED_COUNT + interestTxRows.length}`);
}

seed()
    .catch((err) => {
        console.error('Seed failed:', err);
        process.exit(1);
    })
    .finally(() => process.exit(0));
